site_name: ${{values.component_id | dump}}
site_description: ${{values.description | dump}}
site_author: ${{values.owner | dump}}

nav:
  - Introduction: index.md

plugins:
  - techdocs-core













